name: Test Documentation deployment

on:
  pull_request:
    branches: [master]
    paths: [docs/gh-pages/**]

jobs:
  deploy:
    name: Test Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: curl -fsSL https://get.pnpm.io/install.sh | sh -
      - run: node common/scripts/install-run-rush.js install
      - name: Build documentation
        working-directory: docs/gh-pages
        run: |
          pnpm build