name: Test Documentation deployment

on:
  pull_request:
    branches: [master]
    paths: [docs/gh-pages/**]

jobs:
  deploy:
    name: Test Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.3.0
      - run: node common/scripts/install-run-rush.js install
      - name: Build documentation
        working-directory: docs/gh-pages
        run: |
          pnpm build